### ISSUE TITLE
Multiple Selection Reprocessing Failed."Error: Expression term has unexpected number of values '1111,1112,1113' for 'Id'

### ISSUE THREAD

**Issue by stroomdev42** [gchq/stroom#2579]
1. Procedure works on v6.1
2. Select a single "error" entry in Feed Tab. Select Re-processing icon. This correctly works.
3. Select Multiple "error" entries in Feed Tab. These entries can be listed concurrently or spaced by other entries. In this case selected three non-concurrent entries. Then select Re-processing icon. This does not complete successfully. Also failed with four concurrent entries. 
Looking at Pipeline tab.

Status: Error:Expression Expression term has unexpected number of values '1111,1112,1113'
Minimum Data id:0

OR { Id in 1111,1112,1113}

Id's appear correct(Valid Error Stream Ids).

Using v7.0b155

In v6.1
Pipeline Tab  has 
AND { OR { Id = 8888
                    Id = 8889
The above are the Raw Event Id's not the Error Stream Id's

**Comment by burnalting** [comment]
Same issue in v7.0b156 as per
![image](https://user-images.githubusercontent.com/10084635/142701065-13ccdc1a-1270-452c-9028-31d36afc4e70.png)

and

![image](https://user-images.githubusercontent.com/10084635/142701107-16cd7eba-a4d5-4c00-98e8-3fcb03dc412f.png)

**Comment by stroomdev66** [comment]
Fixed as part of #2574

**Comment by stroomdev42** [comment]
Rechecking
Using v7.0b155 (HS SBX)
If checking Reprocess data: in Create Processors dialog box this issue still does occur.
